config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'privacy', to: 'static_pages#privacy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
  get 'landing', to: 'static_pages#landing'

  devise_for :admins

  devise_scope :admin do
    get "admins/sign_out", to: "devise/sessions#destroy"
  end

  resources :posts, controller: 'posts/posts'

  resources :projects, controller: 'projects/projects'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable, :validatable, :recoverable,
  devise :database_authenticatable, :registerable, :rememberable
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged

  default_scope -> { order('id DESC') }

  belongs_to :admin

  before_save :should_generate_new_friendly_id?, if: :slug_changed?

  private

    def should_generate_new_friendly_id?
      slug_changed?
    end

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged

  default_scope -> { order('id DESC') }

  belongs_to :admin

  before_save :should_generate_new_friendly_id?, if: :slug_changed?

  private

    def should_generate_new_friendly_id?
      slug_changed?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts/posts_controller.rb
class Posts::PostsController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.admin_id = current_admin.id
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id]).destroy
    redirect_to root_url
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :description, :slug, :image)
    end

end

app/controllers/projects/projects_controller.rb
class Projects::ProjectsController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.friendly.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.admin_id = current_admin.id
    if @project.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def edit
    @project = Project.friendly.find(params[:id])
  end

  def update
    @project = Project.friendly.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.friendly.find(params[:id]).destroy
    redirect_to root_url
  end

  private

    def project_params
      params.require(:project).permit(:title, :content, :description, :slug, :image, :project_url, :facebook_url, :twitter_url, :tumblr_url, :googleplay_url, :instagram_url, :snapchat_name, :youtube_url, :github_url, :pinterest_url, :start_date, :end_date, :hours, :logo)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @posts = Post.all
    @projects = Project.all
  end

  def privacy
  end

  def terms_of_use
  end

  def contact
  end

  def about
  end

  def landing
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Alex Heil Rocks"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'partials/shim' %>
  <%= render 'partials/statcounter' %>
</head>
<body>

<%= yield %>

<%= render 'partials/footer' %>

</body>
</html>

app/views/partials/_footer.html.erb
<footer>
  <nav>
    <ul>
      | <li><%= link_to 'home', root_url %></li> |
      <li><%= link_to 'privacy', privacy_path %></li> |
      <li><%= link_to 'contact', contact_path %></li> |
      <li><%= link_to 'future', '#' %></li> |
    </ul>
  </nav>
</footer>
<% if admin_signed_in? %>
<center>hi alex</center>
<% end %>

app/views/partials/_header.html.erb
<header>
  <nav>
    <div class="site-title">
      <a href="http://alexheil.rocks">alexheil<span class="site-title-thin">rocks</span></a>
    </div>
    <ul>
      <li><%= link_to 'about', about_path %></li>
      <li><%= link_to 'blog', posts_path %></li>
      <li><%= link_to 'junk I\'ve made', projects_path %></li>
    </ul>
  </nav>
</header>

app/views/partials/_home_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to 'about', about_path %></li>
      <li><%= link_to 'blog', posts_path %></li>
      <li><%= link_to 'junk I\'ve made', projects_path %></li>
    </ul>
  </nav>
</header>

app/views/partials/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
</script>
<![endif]-->

app/views/partials/_statcounter.html.erb
<script type="text/javascript">
var sc_project=10478288;
var sc_invisible=1;
var sc_security="1f157e2c";
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript><div class="statcounter"><a title="web counter"
href="http://statcounter.com/" target="_blank"><img
class="statcounter"
src="http://c.statcounter.com/10478288/0/1f157e2c/1/"
alt="web counter"></a></div></noscript>

app/views/posts/posts/edit.html.erb
<%= provide(:title,  "Edit " + sanitize(@post.title)) %>

<%= render 'partials/header' %>

<main class="container">
  <div class="form-container">

    <h2>Edit <%= @post.title %></h2>

    <%= form_for(@post, url: post_path) do |f| %>
      <div class="field">
        <%= f.text_field :title, placeholder: "title", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :slug, placeholder: "slug", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :image, placeholder: "image", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_area :description, placeholder: "description", class: "text-area" %>
      </div>
      <div class="field">
        <%= f.text_area :content, placeholder: "content", class: "text-area" %>
      </div>
      <div class="actions">
        <%= f.submit "publish post", class: "submit-button" %>
      </div>
    <% end %>

  </div>
</main>

app/views/posts/posts/index.html.erb
<%= provide(:title,  "All Posts") %>

<%= render 'partials/header' %>


<main class="container">
  <section class="post">

    <% if @posts.any? %>
      <% @posts.each do |post| %>
      <section class="three-space">
        <h2><%= link_to post.title, post_path(post) %></h2>
        <img class="two-space" srcset="<%= post.image %>" width="100%" height="auto" />
        <article>
          <%= sanitize(post.content).split("<h3>").first %>
        </article>
        <div class="one-space">
          <%= link_to "Read more...", post_path(post) %>
        </div>
      </section>
      <% end %>
    <% else %>
      There are no posts on this site lol
    <% end %>

  </section>
</main>

app/views/posts/posts/new.html.erb
<%= provide(:title,  "New Post") %>

<%= render 'partials/header' %>

<main class="container">
  <div class="form-container">

    <h2>New Post</h2>

    <%= form_for(@post, url: posts_path) do |f| %>
      <div class="field">
        <%= f.text_field :title, placeholder: "title", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :slug, placeholder: "slug", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :image, placeholder: "image", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :description, placeholder: "description", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_area :content, placeholder: "content", class: "text-area" %>
      </div>
      <div class="actions">
        <%= f.submit "publish post", class: "submit-button" %>
      </div>
    <% end %>

  </div>
</main>

app/views/posts/posts/show.html.erb
<%= provide(:title,  sanitize(@post.title)) %>

<%= render 'partials/header' %>

<main class="container">
  <section class="post">

    <h2><%=@post.title %></h2>

    <img class="two-space" srcset="<%= @post.image %>" width="100%" height="auto" />

    <span>By Alex Heil. Follow him on Twitter <a href="https://twitter.com/realalexheil">here</a>. <%= link_to "Hello, Alex.", post_path, data: { confirm: "Care for some Mighty Taco?" }, method: :delete if admin_signed_in? %></span>

    <article>
      <%= sanitize(@post.content) %>
    </article>

    <div class="list">
      <h3>Share this on...?</h3>
      <ul>
        <li>
          <a href="https://twitter.com/share" class="twitter-share-button" >Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        </li>
      </ul>
    </div>

    <div class="list">
      <ul>
      <% if Post.exists?(@post.id + 1) %>
          <li>< Next - <%= link_to "#{Post.find(@post.id + 1).title}", post_path(Post.find(@post.id + 1)) %></li>
        <% else %>
        <% end %>
        <% if Post.exists?(@post.id - 1) %>
          <li><%= link_to "#{Post.find(@post.id - 1).title}", post_path(Post.find(@post.id - 1)) %> -  Previous ></li>
        <% else %>
        <% end %>
      </ul>
    </div>

  </section>
</main>

app/views/projects/projects/edit.html.erb
<%= provide(:title,  "Edit " + sanitize(@project.title)) %>

<%= render 'partials/header' %>

<main class="container">
  <div class="form-container">

    <h2>Edit <%= @project.title %></h2>

    <%= form_for(@project, url: project_path) do |f| %>
      <div class="field">
        <%= f.text_field :title, placeholder: "title", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :slug, placeholder: "slug", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :logo, placeholder: "logo", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :image, placeholder: "image", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :description, placeholder: "description", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_area :content, placeholder: "content", class: "text-area" %>
      </div>
      <div class="field">
        <%= f.text_field :start_date, placeholder: "start date", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :end_date, placeholder: "end date", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :hours, placeholder: "hours", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :project_url, placeholder: "project url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :facebook_url, placeholder: "facebook url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :twitter_url, placeholder: "twitter url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :tumblr_url, placeholder: "tumblr url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :googleplay_url, placeholder: "google play url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :instagram_url, placeholder: "instagram url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :github_url, placeholder: "github url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :pinterest_url, placeholder: "pinterest url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :youtube_url, placeholder: "youtube url", class: "text-field" %>
      </div>
      <div class="actions">
        <%= f.submit "edit project", class: "submit-button" %>
      </div>
    <% end %>

  </div>
</main>

app/views/projects/projects/index.html.erb
<%= provide(:title,  "All Posts") %>

<%= render 'partials/header' %>


<main class="container">
  <section class="post">

    <% if @projects.any? %>
      <% @projects.each do |project| %>
      <section class="three-space">
        <h2><%= link_to project.title, project_path(project) %></h2>
        <img class="two-space" srcset="<%= project.logo %>" width="100%" height="auto" />
        <article>
          <%= sanitize(project.description) %>
        </article>
        <div class="one-space">
          <%= link_to "Project details...", project_path(project) %>
        </div>
      </section>
      <% end %>
    <% else %>
      There are no projects on this site lol
    <% end %>

  </section>
</main>

app/views/projects/projects/new.html.erb
<%= provide(:title,  "New Project") %>

<%= render 'partials/header' %>

<main class="container">
  <div class="form-container">

    <h2>New Project</h2>

    <%= form_for(@project, url: projects_path) do |f| %>
      <div class="field">
        <%= f.text_field :title, placeholder: "title", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :slug, placeholder: "slug", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :logo, placeholder: "logo", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :image, placeholder: "image", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :description, placeholder: "description", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_area :content, placeholder: "content", class: "text-area" %>
      </div>
      <div class="field">
        <%= f.text_field :start_date, placeholder: "start date", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :end_date, placeholder: "end date", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :hours, placeholder: "hours", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :project_url, placeholder: "project url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :facebook_url, placeholder: "facebook url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :twitter_url, placeholder: "twitter url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :tumblr_url, placeholder: "tumblr url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :googleplay_url, placeholder: "google play url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :instagram_url, placeholder: "instagram url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :github_url, placeholder: "github url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :pinterest_url, placeholder: "pinterest url", class: "text-field" %>
      </div>
      <div class="field">
        <%= f.text_field :youtube_url, placeholder: "youtube url", class: "text-field" %>
      </div>
      <div class="actions">
        <%= f.submit "publish project", class: "submit-button" %>
      </div>
    <% end %>

  </div>
</main>

app/views/projects/projects/show.html.erb
<%= provide(:title,  sanitize(@project.title)) %>

<%= render 'partials/header' %>

<main class="container">
  <section class="project">

    <div class="two-space center">
      <h1><%= link_to @project.title, @project.project_url %></h1>
    </div>

    <div class="two">
      <img srcset="<%= @project.logo %>" width="100%" height="auto" />
    </div>

    <div class="two">
      <h3>Project description</h3>
      <% if @project.start_date.present? %>
      <div class="one-space">
        <strong>Start date</strong> - <%= @project.start_date %>
      </div>
      <% end %>
      <% if @project.end_date.present? %>
      <div class="one-space">
        <strong>End date</strong> - <%= @project.end_date %>
      </div>
      <% end %>
      <% if @project.hours.present? %>
      <div class="one-space">
        <strong>Hours worked</strong> - <%= @project.hours %>
      </div>
      <% end %>
      <article>
        <%= sanitize(@project.content) %>
      </article>
    </div>

    <div class="project-find">
      <h3>Find this project on...</h3>
      <% if @project.facebook_url.present? %>
      <div class="project-find-icon facebook-icon">
        <%= link_to "", @project.facebook_url, class: "fa fa-facebook" %>
      </div>
      <% end %>
      <% if @project.twitter_url.present? %>
      <div class="project-find-icon twitter-icon">
        <%= link_to "", @project.twitter_url, class: "fa fa-twitter"  %>
      </div>
      <% end %>
      <% if @project.tumblr_url.present? %>
      <div class="project-find-icon tumblr-icon">
        <%= link_to "", @project.tumblr_url, class: "fa fa-tumblr"  %>
      </div>
      <% end %>
      <% if @project.instagram_url.present? %>
      <div class="project-find-icon instagram-icon">
        <%= link_to "", @project.instagram_url, class: "fa fa-instagram"  %>
      </div>
      <% end %>
      <% if @project.youtube_url.present? %>
      <div class="project-find-icon youtube-icon">
        <%= link_to "", @project.youtube_url, class: "fa fa-youtube-play" %>
      </div>
      <% end %>
      <% if @project.pinterest_url.present? %>
      <div class="project-find-icon pinterest-icon">
        <%= link_to "", @project.pinterest_url, class: "fa fa-pinterest" %>
      </div>
      <% end %>
      <% if @project.github_url.present? %>
      <div class="project-find-icon github-icon">
        <%= link_to "", @project.github_url, class: "fa fa-github" %>
      </div>
      <% end %>
      <% if @project.googleplay_url.present? %>
      <div class="project-find-icon android-icon">
        <%= link_to "", @project.googleplay_url, class: "fa fa-android"  %>
      </div>
      <% end %>
    </div>

    <div class="three-space">
      <img srcset="<%= @project.image %>" width="100%" height="auto" />
    </div>

    <div class="list">
      <h3>Share this on...?</h3>
      <ul>
        <li>
          <a href="https://twitter.com/share" class="twitter-share-button" >Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        </li>
      </ul>
    </div>

    <div class="list">
      <ul>
      <% if Project.exists?(@project.id + 1) %>
          <li>< Next - <%= link_to "#{Project.find(@project.id + 1).title}", project_path(Project.find(@project.id + 1)) %></li>
        <% else %>
        <% end %>
        <% if Project.exists?(@project.id - 1) %>
          <li><%= link_to "#{Project.find(@project.id - 1).title}", project_path(Project.find(@project.id - 1)) %> -  Previous ></li>
        <% else %>
        <% end %>
      </ul>
    </div>

  </section>
</main>


app/views/static_pages/about.html.erb
<%= provide(:title,  "About") %>

<%= render 'partials/header' %>

<main class="container">
  <h2>
    About Alex Heil
  </h2>
  <article>
    About me

    my life and

    some other shit
  </article>
</main>

app/views/static_pages/contact.html.erb
<%= provide(:title,  "Contact") %>

<%= render 'partials/header' %>

<main class="container">
  <section class="post">
    <h2>
      Contact
    </h2>
    <article>
      Forms are useless. Contact me on Twitter <a href="https://twitter.com/RealAlexHeil">@RealAlexHeil</a>.
    </article>
  </section>
</main>

app/views/static_pages/home.html.erb
<%= render 'partials/home_header' %>

<section class="hero">
  <div class="home-site-title">
    alexheil<span class="site-title-thin">rocks</span>
  </div>
  <div class="home-site-tagline">
    made in buffalo
  </div>
</section>

<main class="container">

  <% if @posts.any? %>

  <div class="main-title">
    recent blog posts
  </div>

    <% @posts.take(3).each do |post| %>
    <div class="three">
      <div class="mini-img">
        <img srcset="<%= post.image %>" width="100%" height="auto" />
      </div>
      <div class="mini-title two-space">
        <%= link_to post.title, post_path(post) %>
      </div>
      <div class="two-space">
        <%= post.description %>
      </div>
      <div class="two-space">
        <%= link_to "Read this post?", post_path(post) %>
      </div>
    </div>
    <% end %>

  <% end %>

  <% if @projects.any? %>

  <div class="main-title">
    junk I've made recently
  </div>

    <% @projects.take(3).each do |project| %>
    <div class="three">
      <div class="mini-img">
        <img srcset="<%= project.logo %>" width="100%" height="auto" />
      </div>
      <div class="mini-title two-space">
        <%= link_to project.title, project_path(project) %>
      </div>
      <div class="two-space">
        <%= project.description %>
      </div>
      <div class="two-space">
        <%= link_to "View this project?", project_path(project) %>
      </div>
    </div>
    <% end %>

  <% end %>

</main>

<section class="main-find invert">
  <div class="container padding">

    <div class="main-title">
      Find me on...
    </div>

    <div class="five twitter">
      <a href="https://twitter.com/realalexheil">
      <div class="icon">
        <i class="fa fa-twitter"></i>
      </div>
      <div class="mini-title">
        Twitter
      </div>
    </a>
    </div>

    <div class="five instagram">
      <a href="https://instagram.com/alexheil">
      <div class="icon">
        <i class="fa fa-instagram"></i>
      </div>
      <div class="mini-title">
        Instagram
      </div>
      </a>
    </div>

    <div class="five github">
      <a href="https://github.com/alexheil">
      <div class="icon">
        <i class="fa fa-github"></i>
      </div>
      <div class="mini-title">
        GitHub
      </div>
      </a>
    </div>

    <div class="five youtube">
      <a href="https://www.youtube.com/channel/UCAQlbbgqQuMidIyuzPylAQw">
      <div class="icon">
        <i class="fa fa-youtube-play"></i>
      </div>
      <div class="mini-title">
        YouTube
      </div>
      </a>
    </div>

    <div class="five googleplus">
      <a href="https://plus.google.com/u/0/+AlexHeil">
      <div class="icon">
        <i class="fa fa-google-plus"></i>
      </div>
      <div class="mini-title">
        Google+
      </div>
      </a>
    </div>

  </div>
</section>

app/views/static_pages/landing.html.erb
<%= provide(:title,  "Free Updates") %>

<header>
  <h1><%= link_to "psych born", root_url %></h1>
</header>

<main>
  <h2>
    How You Can Use Proven Psychological Methods to Increase Your Happiness, Better Your Memory, and Improve Your Life
  </h2>
  <article>
    Sign up to the Psych Born newsletter for free and you’ll learn how you can use psychology to “get smart” about your life…

    …And then you’ll see why it’s absolutely VITAL that you take advantage of these methods.

    You also gain access to my FREE eBook titled, : ) The REAL Key to the Pursuit of Happiness.

    Guess what?! Those few sentences above this one are old! They don't apply at the moment.

    Why don't I just delete them?

    Good question.

    Because they soon will apply. Once I get more readers on the site.

    <h3>Want free updates?</h3>

    You can do two things:

    First. Follow me on Twitter <a href="https://twitter.com/RealAlexHeil">@RealAlexHeil</a>.

    Share this site with your friends! Once I get 1,000 or so unique visitors per day I'll reopen my email newsletters.

    Until then...
  </article>
</main>

app/views/static_pages/privacy.html.erb
<%= provide(:title,  "Privacy Policy") %>

<%= render 'partials/header' %>

<main class="container">
  <section class="post">
    <h2>
      Privacy Policy
    </h2>
    <article>
      <strong>Effective Date:</strong> <i>October 3rd, 2015</i>

      This will be quick.

      I, Alex Heil, at alexheil.rocks (possibly later referred to as “Site”, “Website”, “I”, “Company”) believe in privacy, but guess what? This isn't some fancy-schmancy website. You're here to look and enjoy the things I've built and maybe disagree with some of my points of view, not sign up and post content on my site.

      Here we go. The following is my privacy policy and is what I do to protect your privacy on my Site.

      <h3>I, personally, do not collect your private information</h3>

      But third parties might!

      Third parties that have access to this Site, such as analytics providers (Google analytics, gotta see those stats, baby), collect and store information automatically whenever you visit one of the pages on this Site, or use any of the services this Site provides. alexheil.rocks automatically sees, collects, and records information on our server logs such as IP address, cookie information, and the page you have requested.

      I will never ask for your credit card information, bank account information, or any private financial information in general, so please never input any of that top secret stuff into any forms on this Site.

      <h3>I, peronsally, do not use cookies</h3>

      But third parties might!

      Third party analytics providers (Google Analytics) will place or recognize a cookie on your browser.

      <h3>I link to external sites!</h3>

      I link to my sites and sites that I find cool. It's never going to be porn, so don't worry. If you think that it's something sketchy don't click on it. I'm not responsible for external site's privacy policies and you need to consult their privacy policy if you are concerned.

      <h3>You don't post anything on my site</h3>

      Enough said there.

      <h3>Please read these next few paragraphs if you are a child or if you are not visiting from the United States of America. Thank you.</h3>

      alexheil.rocks does not knowingly collect, use, maintain, gather, preserve, assemble, or retain any personal information from anyone under the age of 13. No part of this Site is for anyone under the age of 13. Please get the heck out if you are under 13.

      If you are visiting this Site from a country other than the United States of America with different data collection and privacy laws than the data collection and privacy laws of the United States of America, please be aware that you are transferring your data to the United States of America. By providing your information you consent to any transfer and processing in accordance with this Privacy Policy.

      <h3>If this privacy policy changes...</h3>

      …the date at the top of this page will change. Please check back regularly in order to be completely knowledgeable about my privacy policy. Anyone who used this Site prior to the date at the top of this page is subject to the laws and guidelines at the time the information was collected.

      Your continued use of this Site means that you agree and fully understand what’s going on in the revised, updated version of the Privacy Policy.

      Oh, and guess what?

      I reserve the right to change this Privacy Policy at any time. At any minute, any day, any second, any hour this policy can be changed by me, myself, and I.
    </article>
  </section>
</main>

app/views/static_pages/terms_of_use.html.erb
<%= provide(:title,  "Terms of Use") %>

<header>
  <h1><%= link_to "psych born", root_url %></h1>
</header>

<main>
  <h2>
    Terms of Use
  </h2>
  <article>
    Please use the site responsibly.

    <h3>At the moment...</h3>

    There are no services on this site, therefore there is nothing to purchase, meaning no payments will be taken, thus no refunds are available.

    You don’t post any content on my site, so you do not have any proprietary rights to anything on this site, and do not have to follow any sort of content creation code of conduct.

    Please read the <%= link_to "privacy policy", privacy_path %>.

    I will and can change this Terms of Service whenever I want to.

    If you think that I have violated your copyright in any way, tweet me <a href="https://twitter.com/RealAlexHeil">@RealAlexHeil</a>. We will discuss from there.

    This site links to external sites and I am not responsible for what you do on those sites. Oh, and it’s possible it may be an affiliate link. If that’s the case I may make money through affiliate sales.

    That’s it.
  </article>
</main>